<?xml version="1.0" encoding="UTF-8"?>
   <!DOCTYPE personas [
	   <!ELEMENT personas (persona+)>
       <!ELEMENT persona (nombre, nacimiento?, direccion+, hombre | mujer)>
	   <!ELEMENT nombre (#PCDATA)>
	   <!ELEMENT nacimiento EMPTY>
	   <!ATTLIST nacimiento 
			dia    CDATA #REQUIRED
			mes    CDATA #REQUIRED
			ano    CDATA #REQUIRED    
		>
	   <!ELEMENT direccion (calle,poblacion,provincia,cpostal)>
	   <!ELEMENT calle (#PCDATA)>
	   <!ELEMENT poblacion (#PCDATA)>
	   <!ELEMENT provincia (#PCDATA)>
	   <!ELEMENT cpostal (#PCDATA)>			   
	   <!ELEMENT hombre (EMPTY)>
	   <!ELEMENT mujer (EMPTY)>
]>
    <personas>
        <persona>
            <nombre>John Smith</nombre>
            <nacimiento dia="21" mes="Enero" anio="1969"></nacimiento>
            <direccion>
                <calle>Avda. Universidad, 30</calle>
                <poblacion>Leganes</poblacion>
                <provincia>Madrid</provincia>
                <cpostal>28911</cpostal>
            </direccion>
            <hombre/>
        </persona>
    </personas>